Tirth patel
OpenMinds-LCIT/cardiovascular-disease-prediction pull request #45
Opened 2024-02-09 00:26 UTC by tirth-patel01

learn Panda and work with data and data exploration.

2024-02-09 00:51 UTC, prakash-pun requested changes

2024-02-09 00:51 UTC, prakash-pun commented on src/alco_corr_cardio.py
> +from matplotlib import pyplot as plt
move this import to top

2024-02-09 01:41 UTC, tirth-patel01 commented on src/alco_corr_cardio.py
> +from matplotlib import pyplot as plt
ok done.

2024-02-09 01:41 UTC, tirth-patel01 commented on src/alco_corr_cardio.py
> +from matplotlib import pyplot as plt
please check it and merge

2024-02-10 00:55 UTC, amannain122 approved these changes
Please co relate with target variable and try scaling.

2024-02-10 00:57 UTC, merged